package com.epam.webapp.constant;

public class ConstName {

  public static final String WRONG_ACTION = "wrongAction";
  public static final String COMMAND = "command";
  public static final String DATE = "date";
  public static final String TASK_ID = "taskId";
  public static final String MARK = "mark";
  public static final String REDIRECT_TO = "redirectTo";
  public static final String DATE_PATTERN = "MM/dd/yyyy";
  public static final String TRAINING_ID = "trainingId";
  public static final String TASK_NAME = "taskName";
  public static final String TASK_TEXT = "taskText";
  public static final String TOPICS_NAME = "topicsName";
  public static final String TOPICS_TEXT = "topicsText";
  public static final String USER_ID = "userId";
  public static final String LOGIN = "login";
  public static final String PASSWORD = "password";
  public static final String USER = "user";
  public static final String MENTOR_ID = "mentorId";
  public static final String DESCRIPTION = "description";
  public static final String GRADE = "grade";
  public static final String TYPE_OPERATION = "typeOperation";
  public static final String TOPIC_ID = "topicId";
  public static final String STUDENT_ID = "studentId";
  public static final String NAME = "name";
  public static final String SURNAME = "surname";
  public static final String EMAIL = "email";
  public static final String TYPE = "type";
  public static final String AGREEMENT = "agreement";
  public static final String CONSULTATION_ID = "consultationId";
  public static final String ORDER_SENT_MESSAGE = "orderSentMessage";
  public static final String SOLUTION = "solution";
  public static final String SHOW = "showSolution";
  public static final String EDITOR = "editor";
  public static final String INFORMATION = "information";
  public static final String TRAINING_NAME = "trainingName";
  public static final String TASK = "task";
  public static final String TOPIC_NAME = "topicName";
  public static final String TOPIC = "topic";
  public static final String USER_TYPE = "type";
  public static final String USER_STATUS = "status";
  public static final String CONTROLLER = "controller";
  public static final String REFERER = "referer";
  public static final String NULL_PAGE = "nullPage";
  public static final String CARD_ID = "cardId";
  public static final String SUM = "sum";
  public static final String CARD_DONOR = "cardDonor";
  public static final String CART_RECIPIENT = "cardRecipient";
  public static final String PRICE = "price";
  public static final String REPEAT_PASSWORD ="repeatPassword";
  public static final String USER_FIELDS = "userFields";
  public static final String FEEDBACK = "feedback";
}
